export const INDICES_AND_FOREX = [
    { value: "US500", label: "US 500" },
    { value: "US30", label: "US 30" },
    { value: "US100", label: "US 100" },
    { value: "US2000", label: "US 2000" },
    { value: "UK100", label: "UK 100" },
    { value: "DE40", label: "DAX 40" },
    { value: "FR40", label: "CAC 40" },
    { value: "EU50", label: "Euro Stoxx 50" },
    { value: "JP225", label: "Nikkei 225" },
    { value: "HK50", label: "Hang Seng" },
    { value: "CN50", label: "Shanghai Composite" },
    { value: "AU200", label: "ASX 200" },
    { value: "IN50", label: "Nifty 50" },
    { value: "SA40", label: "South Africa 40" },
    { value: "EUR/USD", label: "EUR/USD" },
    { value: "GBP/USD", label: "GBP/USD" },
    { value: "USD/JPY", label: "USD/JPY" },
    { value: "USD/CHF", label: "USD/CHF" },
    { value: "AUD/USD", label: "AUD/USD" },
    { value: "USD/CAD", label: "USD/CAD" },
    { value: "NZD/USD", label: "NZD/USD" },
    { value: "EUR/GBP", label: "EUR/GBP" },
    { value: "EUR/JPY", label: "EUR/JPY" },
    { value: "GBP/JPY", label: "GBP/JPY" },
    { value: "AUD/NZD", label: "AUD/NZD" },
    { value: "USD/SEK", label: "USD/SEK" },
    { value: "USD/NOK", label: "USD/NOK" },
    { value: "USD/TRY", label: "USD/TRY" },
    { value: "EUR/TRY", label: "EUR/TRY" },
    { value: "USD/ZAR", label: "USD/ZAR" },
    { value: "XAU/USD", label: "XAU/USD" },
    { value: "XAG/USD", label: "XAG/USD" },
    { value: "WTI/USD", label: "WTI/USD" },
    { value: "BRENT/USD", label: "BRENT/USD" },
    { value: "NG/USD", label: "NG/USD" }
  ];
  